# -*- coding: utf-8 -*-
"""
Loads Data generated by class_HIC and filters fine-scale coefficients
"""

import os
import sys
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import pickle
import torch
import pywt
import argparse
import yaml
from pathlib import Path
from mpl_toolkits.axes_grid1 import make_axes_locatable

# Add the parent directory (src) to the Python path
current_dir = Path(__file__).resolve().parent  # src/viz/
src_dir = current_dir.parent  # src/
sys.path.insert(0, str(src_dir))

# Import from existing files
from utils.io import load_paths

paths = load_paths()

def get_finest_scales_for_wavelet(wavelet, total_levels):
    """
    Get the finest scale levels for a given wavelet (where hallucinations are most likely)
    
    Args:
        wavelet: Wavelet type ('haar', 'db4', 'db8', 'db12')
        total_levels: Total number of detail levels available
        num_scales: Number of finest scales to use (default: 2)
    
    Returns:
        finest_levels: List of level indices for finest scales
        level_description: String description of the levels
    """
    # control mapping based on wavelet type
    wavelet_finest_mapping = {
        'haar': [5, 6],    # Levels 6 and 7 (indices 5, 6 for 32x32, 64x64 coeffs)
        'db4': [2, 3],     # Levels 3 and 4 (indices 2, 3 for 32x32, 64x64 coeffs)  
        'db8': [1, 2],     # Levels 2 and 3 (indices 1, 2 for 32x32, 64x64 coeffs)
        'db12': [0, 1]     # Levels 1 and 2 (indices 0, 1 for 32x32, 64x64 coeffs)
    }
    
    finest_levels = wavelet_finest_mapping[wavelet]
    # Filter out levels that don't exist
    finest_levels = [level for level in finest_levels if level < total_levels]
    level_description = f"L{'+L'.join([str(i+1) for i in finest_levels])}"
    
    
    return finest_levels, level_description

def decompose_image_with_frequency_structure(image, wavelet='db8', mode='periodization'):
    """
    Decompose a single 2D image into wavelet coefficients preserving frequency band structure
    
    Args:
        image: 2D numpy array
        wavelet: wavelet type
        mode: wavelet mode
        
    Returns:
        coeffs_structure: List of tuples (cA, (cH, cV, cD)) for each level
        coeffs_flat: Flattened coefficients matching the original class_HIC code
        band_info: Information about which coefficients belong to which bands
    """
    # Perform wavelet decomposition
    coeffs = pywt.wavedec2(image, wavelet, mode=mode)
    
    # Skip LL coefficients 
    detail_coeffs = coeffs[1:]
    
    # Create band information for mapping flat indices to frequency bands
    band_info = []
    coeffs_flat = []
    flat_idx = 0
    
    for level_idx, (cH, cV, cD) in enumerate(detail_coeffs):
        # Store information about each frequency band
        level_info = {
            'level': level_idx,
            'HH': {'shape': cD.shape, 'start_idx': flat_idx, 'end_idx': flat_idx + cD.size},
            'HL': {'shape': cH.shape, 'start_idx': flat_idx + cD.size, 'end_idx': flat_idx + cD.size + cH.size},
            'LH': {'shape': cV.shape, 'start_idx': flat_idx + cD.size + cH.size, 'end_idx': flat_idx + cD.size + cH.size + cV.size}
        }
        
        # Flatten coefficients in the same order as original code: HH, HL, LH
        coeffs_flat.extend(cD.flatten())  # HH (high-high)
        coeffs_flat.extend(cH.flatten())  # HL (high-low)
        coeffs_flat.extend(cV.flatten())  # LH (low-high)
        
        flat_idx += cD.size + cH.size + cV.size
        band_info.append(level_info)
    
    return coeffs, coeffs_flat, band_info

def reconstruct_from_frequency_and_class_filter(image, R_values, coefficient_classes, class_idx, 
                                              frequency_bands=None, levels=None, wavelet='db8', mode='periodization'):
    """
    Reconstruct image using both class-based and level/frequency-based filtering
    
    Args:
        image: Original image [H, W]
        R_values: R values for this image [total_coeffs] - can be None
        coefficient_classes: Dictionary mapping class indices to coefficient indices
        class_idx: Class to reconstruct (0, 1, 2, 3)
        frequency_bands: List of frequency bands to include ['HH', 'HL', 'LH'] or None for all
        levels: List of levels to include [0, 1, 2, 3] or None for all (0=Level1, 1=Level2, etc.)
        wavelet: Wavelet type
        mode: Wavelet mode
        
    Returns:
        reconstructed_image: Reconstructed image
    """
    # Get wavelet decomposition with frequency structure
    coeffs, coeffs_flat, band_info = decompose_image_with_frequency_structure(image, wavelet, mode)
    
    # Get coefficients in this class - convert to set of indices relative to this specific image
    class_coefficient_indices = set(coefficient_classes[class_idx])
    
    # Create masks for filtering
    if frequency_bands is None:
        frequency_bands = ['HH', 'HL', 'LH']
    
    # Initialize filtered coefficients - start with zeros
    filtered_coeffs = []
    
    # Handle approximation coefficients - they were excluded from original HIC classification
    # For reconstruction without them, we need to provide zero LL coefficients to maintain proper structure
    cA = np.zeros_like(coeffs[0])  
    filtered_coeffs.append(cA)  
    
    # Process each decomposition level
    for level_idx, (cH, cV, cD) in enumerate(coeffs[1:]):
        level_info = band_info[level_idx]
        
        # Initialize filtered bands
        filtered_cH = np.zeros_like(cH)
        filtered_cV = np.zeros_like(cV) 
        filtered_cD = np.zeros_like(cD)
        
        if level_idx in levels:
            # Filter HH band (diagonal details - cD)
            if 'HH' in frequency_bands:
                hh_info = level_info['HH']
                for flat_idx in range(hh_info['start_idx'], hh_info['end_idx']):
                    if flat_idx in class_coefficient_indices:
                        # Convert flat index to 2D coordinates within this level
                        local_idx = flat_idx - hh_info['start_idx']
                        i, j = np.unravel_index(local_idx, hh_info['shape'])
                        filtered_cD[i, j] = cD[i, j]
            
            # Filter HL band (horizontal details - cH)
            if 'HL' in frequency_bands:
                hl_info = level_info['HL']
                for flat_idx in range(hl_info['start_idx'], hl_info['end_idx']):
                    if flat_idx in class_coefficient_indices:
                        local_idx = flat_idx - hl_info['start_idx']
                        i, j = np.unravel_index(local_idx, hl_info['shape'])
                        filtered_cH[i, j] = cH[i, j]
            
            # Filter LH band (vertical details - cV)
            if 'LH' in frequency_bands:
                lh_info = level_info['LH']
                for flat_idx in range(lh_info['start_idx'], lh_info['end_idx']):
                    if flat_idx in class_coefficient_indices:
                        local_idx = flat_idx - lh_info['start_idx']
                        i, j = np.unravel_index(local_idx, lh_info['shape'])
                        filtered_cV[i, j] = cV[i, j]
        
        filtered_coeffs.append((filtered_cH, filtered_cV, filtered_cD))
    
    # Reconstruct the image
    reconstructed_image = pywt.waverec2(filtered_coeffs, wavelet, mode=mode)
    
    return reconstructed_image

def convert_global_to_local_coefficient_indices(coefficient_classes, image_idx, n_images, n_channels, n_coeffs):
    """
    Convert global coefficient indices to local indices for a specific image
    
    Args:
        coefficient_classes: Dictionary with global coefficient indices
        image_idx: Index of the image we want (0-3)
        n_images: Total number of images (4)
        n_channels: Number of channels (1)
        n_coeffs: Number of coefficients per image
        
    Returns:
        local_coefficient_classes: Dictionary with local indices for the specific image
    """
    local_coefficient_classes = {}
    
    # Calculate the range of global indices for this specific image
    start_global_idx = image_idx * n_channels * n_coeffs
    end_global_idx = start_global_idx + n_channels * n_coeffs
    
    print(f"Converting global indices to local for image {image_idx}")
    print(f"Global range for this image: [{start_global_idx}, {end_global_idx})")
    
    for class_idx, global_indices in coefficient_classes.items():
        local_indices = []
        for global_idx in global_indices:
            if start_global_idx <= global_idx < end_global_idx:
                # Convert to local index within this image
                local_idx = global_idx - start_global_idx
                # Since we have 1 channel, further reduce by channel
                local_idx = local_idx % n_coeffs
                local_indices.append(local_idx)
        
        local_coefficient_classes[class_idx] = local_indices
        print(f"  Class {class_idx}: {len(global_indices)} global -> {len(local_indices)} local coefficients")
    
    return local_coefficient_classes

def load_all_models_classification_data(model_configs_dict, paths, image_idx=0, wavelet='db8'):
    """
    Load classification data for all models with proper file naming convention
    
    Args:
        model_configs_dict: Dictionary of model names to config paths
        paths: Paths configuration
        image_idx: Image index within batch (0-3)
        wavelet: Wavelet type (e.g., 'db8', 'db12')
        
    Returns:
        Dictionary mapping model names to their loaded data
    """
    all_models_data = {}
    
    # Define model name mapping
    model_name_mapping = {
        'U-Net_L1_Loss': 'U1',
        'U-Net_L2_Loss': 'U2', 
        'SUNet_L1_Loss': 'SU1',
        'SUNet_L2_Loss': 'SU2',
        'LearnLet_L1_Loss': 'L1',
        'LearnLet_L2_Loss': 'L2'
    }
    
    print(f"Loading data for all models with {wavelet} wavelet...")
    
    for model_name, config_path in model_configs_dict.items():
        print(f"  Loading {model_name}...")
        
        try:
            # Load model configuration to get directory
            with open(config_path, 'r') as config:
                opt = yaml.safe_load(config)
            
            Train = opt['TRAINING']
            SUNet = opt['SWINUNET']
            
            # Build model directory path
            model_dir = os.path.join(Train['SAVE_DIR'], SUNet['MODEL_NAME'], Train['LOSS'])
            if not os.path.isabs(model_dir):
                project_root = paths['configs_dir'].parent
                model_dir = str(project_root / model_dir)
            
            print(f"    Model directory: {model_dir}")
            

            classification_dir = os.path.join(model_dir, f'wavelet_{wavelet}_classification')
            if not os.path.exists(classification_dir):
                print(f"    Classification directory not found: {classification_dir}")
                all_models_data[model_name_mapping[model_name]] = None
                continue
            
            analysis_files = [f for f in os.listdir(classification_dir) if f.endswith('_analysis_results.pkl') and not f.endswith('_high.pkl')]
           
            
            if not analysis_files:
                print(f"    No analysis results found in {classification_dir}")
                all_models_data[model_name_mapping[model_name]] = None
                continue
            
            analysis_path = os.path.join(classification_dir, analysis_files[0])
            print(f"    Loading from: {analysis_path}")
            
            with open(analysis_path, 'rb') as f:
                analysis_results = pickle.load(f)
            
            # Load original data from model_predictions directory
            pred_dir = os.path.join(model_dir, 'wavelet_model_predictions')
            if not os.path.exists(pred_dir):
                print(f"    Model predictions directory not found: {pred_dir}")
                all_models_data[model_name_mapping[model_name]] = None
                continue
            
            # Load the prediction data
            predictions = np.load(os.path.join(pred_dir, f'predictions_{model_name}.npy'))
            targets = np.load(os.path.join(pred_dir, 'original_targets.npy'))
            inputs = np.load(os.path.join(pred_dir, 'original_inputs.npy'))
            selected_indices = np.load(os.path.join(pred_dir, 'selected_indices.npy'))
            
            model_data = {
                'analysis_results': analysis_results,
                'predictions': predictions,
                'targets': targets,
                'inputs': inputs,
                'selected_indices': selected_indices,
                'coefficient_classes': analysis_results['coefficient_classes'],
                'classification_stats': analysis_results['classification_stats']
            }
            
            all_models_data[model_name_mapping[model_name]] = model_data
            print(f"    Successfully loaded {model_name} -> {model_name_mapping[model_name]}")
            
        except Exception as e:
            print(f"    Error loading {model_name}: {e}")
            all_models_data[model_name_mapping[model_name]] = None
    
    return all_models_data

def create_multi_model_comparison_plot(all_models_data, output_dir, image_idx=0, target_index=None, wavelet='db8'):
    """
    Create a 2x7 grid plot comparing all models
    Row 1: Ground Truth, PredU1, PredU2, PredSU1, PredSU2, PredL1, PredL2
    Row 2: Empty, HallU1, HallU2, HallSU1, HallSU2, HallL1, HallL2
    
    Args:
        all_models_data: Dictionary containing data for all models
        output_dir: Output directory for saving plots
        image_idx: Index within the batch (0-3)
        target_index: Original dataset index for filename
        wavelet: Wavelet type 
    """
    
    os.makedirs(output_dir, exist_ok=True)
    
    # Model order for display
    model_order = ['U1', 'U2', 'SU1', 'SU2', 'L1', 'L2']
    
    # Model title mapping for proper display names
    model_title_mapping = {
        'U1': 'U-Net L1',
        'U2': 'U-Net L2', 
        'SU1': 'SUNet L1',
        'SU2': 'SUNet L2',
        'L1': 'Learnlets L1',
        'L2': 'Learnlets L2'
    }
    
    # Get target index from any available data
    if target_index is None:
        for model_short, data in all_models_data.items():
            if data is not None:
                target_index = data['selected_indices'][image_idx]
                break
    
    # Get ground truth from any available data (should be the same across all models)
    target = None
    for model_short, data in all_models_data.items():
        if data is not None:
            target = data['targets'][image_idx, 0]
            break
    
    if target is None:
        print("Error: No valid data found in any model")
        return
    
    fig, axes = plt.subplots(2, 7, figsize=(35, 10))
    
    cmap = 'viridis'
    
    all_predictions = []
    all_predictions.append(target)
    
    for model_short in model_order:
        data = all_models_data.get(model_short)
        if data is not None:
            prediction = data['predictions'][image_idx, 0]
            all_predictions.append(prediction)
    
    if all_predictions:
        vmin = min([img.min() for img in all_predictions])
        vmax = max([img.max() for img in all_predictions])
    else:
        vmin, vmax = target.min(), target.max()
    
    # Row 1, Column 0: Ground Truth
    axes[0, 0].imshow(target, cmap=cmap, vmin=vmin, vmax=vmax, aspect='equal')
    axes[0, 0].set_title('Ground Truth', fontsize=18, fontweight='bold')
    axes[0, 0].axis('off')
    
    # Row 1, Columns 1-6: Model Predictions
    for col, model_short in enumerate(model_order, 1):
        data = all_models_data.get(model_short)
        
        if data is not None:
            prediction = data['predictions'][image_idx, 0]
            axes[0, col].imshow(prediction, cmap=cmap, vmin=vmin, vmax=vmax, aspect='equal')
            axes[0, col].set_title(model_title_mapping[model_short], fontsize=18, fontweight='bold')
        else:
            axes[0, col].text(0.5, 0.5, f'{model_title_mapping[model_short]}\nNo Data', ha='center', va='center',
                             transform=axes[0, col].transAxes, fontsize=10, style='italic')
            axes[0, col].set_title(model_title_mapping[model_short], fontsize=18, fontweight='bold')
        
        axes[0, col].axis('off')
    
    # Row 2, Column 0: Empty
    axes[1, 0].axis('off')
    
    # First pass: Collect all hallucination maps to determine common color range
    print("Computing common color range for hallucination maps...")
    all_hallucination_maps = {}
    hall_min_vals = []
    hall_max_vals = []
    
    for model_short in model_order:
        data = all_models_data.get(model_short)
            
        # Extract data for this model
        prediction = data['predictions'][image_idx, 0]
        global_coefficient_classes = data['coefficient_classes']
        
        # Convert global coefficient indices to local indices for this specific image
        _, coeffs_flat, _ = decompose_image_with_frequency_structure(prediction, wavelet, 'periodization')
        n_coeffs = len(coeffs_flat)
        n_images, n_channels = data['predictions'].shape[:2]
        
        coefficient_classes = convert_global_to_local_coefficient_indices(
            global_coefficient_classes, image_idx, n_images, n_channels, n_coeffs
        )
        
        # Create Class 3 hallucination map using wavelet-specific finest scales
        if 3 in coefficient_classes and len(coefficient_classes[3]) > 0:
            # Use wavelet-specific finest levels based on analysis
            _, coeffs_flat_temp, band_info_temp = decompose_image_with_frequency_structure(prediction, wavelet, 'periodization')
            total_levels = len(band_info_temp)  
            
            # Get wavelet-specific finest levels
            finest_levels, level_description = get_finest_scales_for_wavelet(
                wavelet, total_levels
            )
            
            class3_recon = reconstruct_from_frequency_and_class_filter(
                prediction, None, coefficient_classes, class_idx=3, 
                frequency_bands=['HH', 'HL', 'LH'], levels=finest_levels,
                wavelet=wavelet, mode='periodization'
            )
            
            # Store for plotting and collect range info
            if np.max(np.abs(class3_recon)) > 1e-10:  # Check if there's actual content
                all_hallucination_maps[model_short] = class3_recon
                hall_min_vals.append(class3_recon.min())
                hall_max_vals.append(class3_recon.max())
        
    
    # Determine common color range for hallucination maps
    if hall_min_vals and hall_max_vals:
        hall_vmin = min(hall_min_vals)
        hall_vmax = max(hall_max_vals)
    
    # Second pass: Plot all hallucination maps with common color range
    im_hall = None  # Store an image for colorbar reference
    for col, model_short in enumerate(model_order, 1):
        class3_recon = all_hallucination_maps.get(model_short)
        
        if class3_recon is not None:
            # Plot with common color range
            im_hall = axes[1, col].imshow(class3_recon, cmap=cmap, vmin=hall_vmin, vmax=hall_vmax, aspect='equal')
            # No title for bottom row
        else:
            # Handle cases with no data/content/errors
            data = all_models_data.get(model_short)
            if data is None:
                axes[1, col].text(0.5, 0.5, f'No Data', ha='center', va='center',
                                 transform=axes[1, col].transAxes, fontsize=10, style='italic')
            else:
                # Check if it's no content or no Class 3
                prediction = data['predictions'][image_idx, 0]
                global_coefficient_classes = data['coefficient_classes']
                _, coeffs_flat, _ = decompose_image_with_frequency_structure(prediction, wavelet, 'periodization')
                n_coeffs = len(coeffs_flat)
                n_images, n_channels = data['predictions'].shape[:2]
                coefficient_classes = convert_global_to_local_coefficient_indices(
                    global_coefficient_classes, image_idx, n_images, n_channels, n_coeffs
                )
                
                if 3 not in coefficient_classes or len(coefficient_classes[3]) == 0:
                    axes[1, col].text(0.5, 0.5, f'No Class 3', ha='center', va='center',
                                     transform=axes[1, col].transAxes, fontsize=10, style='italic')
                else:
                    axes[1, col].text(0.5, 0.5, f'No Content', ha='center', va='center',
                                     transform=axes[1, col].transAxes, fontsize=10, style='italic')
            
        
        axes[1, col].axis('off')
    
    if all_predictions:
        plt.subplots_adjust(right=0.93, left=0.03, top=0.88, bottom=0.02)
        
        fig.text(0.02, 0.7, 'Predictions', fontsize=18, fontweight='bold', 
                rotation=90, va='center', ha='center')
        fig.text(0.02, 0.25, 'Hallucinations', fontsize=18, fontweight='bold', 
                rotation=90, va='center', ha='center')
        
        # Colorbar for predictions (top row)
        pred_cbar_ax = fig.add_axes([0.94, 0.49, 0.015, 0.39])  # [left, bottom, width, height]
        pred_cbar = plt.colorbar(axes[0, 1].get_images()[0], cax=pred_cbar_ax, orientation='vertical')
        pred_cbar.set_label('', fontsize=12, fontweight='bold')
        pred_cbar.ax.tick_params(labelsize=12)
        
        # Colorbar for hallucination maps (bottom row) 
        if im_hall is not None:
            hall_cbar_ax = fig.add_axes([0.94, 0.02, 0.015, 0.39])  # [left, bottom, width, height]
            hall_cbar = plt.colorbar(im_hall, cax=hall_cbar_ax, orientation='vertical')
            hall_cbar.set_label('', fontsize=12, fontweight='bold')
            hall_cbar.ax.tick_params(labelsize=12)
    
    
    # Save the plot
    output_filename = f"multi_model_comparison_{wavelet}_index_{target_index}.png"
    output_path = os.path.join(output_dir, output_filename)
    plt.savefig(output_path, dpi=150, bbox_inches='tight', facecolor='white', edgecolor='none')
    print(f"Saved: {output_path}")
    

def main():
    """Main function to create frequency-class reconstruction plots"""
    
    parser = argparse.ArgumentParser(description="Create frequency and class-based reconstruction plots")
    parser.add_argument("--image-idx", type=int, default=0,
                       help="Image index within batch (0-3)")
    parser.add_argument("--wavelet", type=str, default="db8",
                       help="Wavelet type")
    
    args = parser.parse_args()
    
    # Model configs
    model_configs = {
        'U-Net_L1_Loss': (paths['configs_dir'] / 'training_UNet_L1.yaml'),
        'U-Net_L2_Loss': (paths['configs_dir'] / 'training_UNet_L2.yaml'),
        'SUNet_L1_Loss': (paths['configs_dir'] / 'training_SUNet_L1.yaml'),
        'SUNet_L2_Loss': (paths['configs_dir'] / 'training_SUNet_L2.yaml'),
        'LearnLet_L1_Loss': (paths['configs_dir'] / 'training_LeLet_L1.yaml'),
        'LearnLet_L2_Loss': (paths['configs_dir'] / 'training_LeLet_L2.yaml'),
    }
    
    
    plot_type = "multi-model comparison"
    
    print(f"Creating {plot_type} ")
    print(f"Image index: {args.image_idx}")
    print(f"Wavelet: {args.wavelet}")
    
    # Load model configuration to get directory
    yaml_path = model_configs[args.model]
    with open(yaml_path, 'r') as config:
        opt = yaml.safe_load(config)
    
    Train = opt['TRAINING']
    SUNet = opt['SWINUNET']
    
    # Build model directory path
    model_dir = os.path.join(Train['SAVE_DIR'], SUNet['MODEL_NAME'], Train['LOSS'])
    if not os.path.isabs(model_dir):
        project_root = paths['configs_dir'].parent
        model_dir = str(project_root / model_dir)
    
    print(f"Model directory: {model_dir}")
    
    # Create output directory
    output_dir = os.path.join(paths['results_dir'], 'level_class_analysis')
    
    # Load data for all models with specified wavelet
    print(f"Loading data for all models with {args.wavelet} wavelet...")
    all_models_data = load_all_models_classification_data(model_configs, paths, args.image_idx, args.wavelet)
    
    # Create multi-model comparison plot
    create_multi_model_comparison_plot(
        all_models_data, output_dir, args.image_idx, wavelet=args.wavelet
    )
    print(f"Successfully created multi-model comparison plot!")


if __name__ == "__main__":
    main()